# Generated by Django 4.1.6 on 2023-02-12 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
